# Generated by Django 5.1.2 on 2024-10-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='jenis',
        ),
        migrations.AddField(
            model_name='surat',
            name='jenis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surat.jenis'),
            preserve_default=False,
        ),
    ]
